<?php
/**
* Implements hook_menu().
*/
function lzoom_menu() {
  $items['lzoom-test'] = array(
    'title' => " ",
    'description' => 'Test using Locus Zoom',
    'page callback' => 'lzoom_test',
    'access callback' => TRUE,
  );
  $items['lzoom-test-1'] = array(
    'title' => " ",
    'description' => 'Locus Zoom plot with fixed input',
    'page callback' => 'lzoom_viz',
    'page arguments' => array('10:114550452-115067678'),
    'access callback' => TRUE,
  );
    $items['lzoom'] = array(
    'title' => 'Interactive Plot of Genetic Association Data',
    'description' => 'Locus Zoom visualization',
    'page callback' => 'lzoom_plot',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['lzoom-data'] = array(
    'title' => " ",
    'description' => 'Locus Zoom Post',
    'page callback' => 'lzoom_post',
    'access callback' => TRUE,
  );


  return $items;
}

function lzoom_libraries_info() {
  $libraries = array();
  $libraries['locuszoom'] = array(
    'name' => 'Locus Zoom',
    'vendor url' => 'http://locuszoom.sph.umich.edu/',
    'download url' => 'https://github.com/statgen/locuszoom',
    'version callback' => '_short_circuit_version',
    'files' => array(
      'js' => array(
        'locuszoom.vendor.min.js',
        'locuszoom.app.js',
      ),
      'css' => array(
        'locuszoom.css'
      ),
    ),
  );

  return $libraries;
}

function lzoom_test() {
  $path = libraries_get_path('locuszoom');
  libraries_load('locuszoom');
  drupal_add_js($path . '/locuszoom.vendor.min.js');
  drupal_add_js($path . '/locuszoom.app.js');
  drupal_add_js($path . '/assets/js/vendor/d3.min.js');
  drupal_add_css($path . '/locuszoom.css');


  //$test = $path . '/index.html';

  $test = file_get_contents($path . '/igap_stage1.html');
  //$test = file_get_contents($path . '/index_drupal.html');

  //$page_text = "<p>Locus Zoom page</p><p></p>" . $path . "<p></p><p></p>";

  return ($test);

}

/**
* Short-circuit the version argument.
*/
function _short_circuit_version() {
  return TRUE;
}

/** Most of above is the test code **/


function lzoom_post() {

 //  $full_url = "https://portaldev.sph.umich.edu/api/v1/statistic/single/results/?filter=analysis%20in%203%20and%20chromosome%20in%20%20%2710%27%20and%20position%20ge%20114550452%20and%20position%20le%20115067678";
//
//   $my_test = drupal_http_request($full_url);
//   $data = drupal_json_decode($my_test->data);
//
//   //dsm($data);
//
//   $lzoom_url = $GLOBALS['base_url'] . "/lzoom-data/results";
//
// //http://localhost:8888/lzoom-data/results/?filter=analysis in 3 and chromosome in  '10' and position ge 114550452 and position le 115067678
//
//   $filter_string = "analysis in 3 and chromosome in '10' and position ge 114550452 and position le 115067678";
//
//   $options = array(
//                   'method' => 'POST',
//                   'data' => $data,
//                   'timeout' => 15,
//                   'headers' => array('Content-Type' => 'application/json', 'Accept' => 'application/json'),
//           );

  //$result = drupal_http_request($post_url, $options);

  $test = _query_mongo_lzoom(10, 114550452, 130901927, 3);

  $test2 = json_encode($test, JSON_UNESCAPED_SLASHES);

  //return drupal_json_output($test, JSON_UNESCAPED_SLASHES);

  return $test2;

}


function lzoom_viz($data_region, $study) {

  $_SESSION['lzoom_data_region'] = $data_region;

  $chart = array(
        'id' => 'plot',
        'type' => 'lzoom',
        'study' => $study,
  );

  return d3_draw($chart);
}



function lzoom_theme() {
    $path = drupal_get_path('module', 'lzoom');
    return array(
        'lzoom' => array('template' => 'lzoom', 'path' => $path),
    );
}

function lzoom_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'lzoom');
  // Override the content type summary info.
  //dsm($theme_registry['d3']);
  if (isset($theme_registry['d3']['template'])) {
    //dsm($theme_registry['d3']);
    $theme_registry['d3']['template'] = $path . '/lzoom';
    //dsm($theme_registry['d3']);
  }
  if (isset($theme_registry['d3']['preprocess functions'])) {
    //dsm($theme_registry['d3']);
    $theme_registry['d3']['preprocess functions'][4] = 'template_preprocess_lzoom';
    //dsm($theme_registry['d3']);
  }
  //dsm($theme_registry['d3']);

}

function template_preprocess_lzoom(&$variables) {

  // Define default data region as APOE
  if (isset($_SESSION['lzoom_data_region'])) {
    $variables['data_region'] =  $_SESSION['lzoom_data_region'];
  } else {
    $variables['data_region'] = '19:44909011-45912650';
  }

  return $variables;
}

function lzoom_plot() {

  $gene_form = drupal_get_form('lzoom_form');
  $output = drupal_render($gene_form);

  return $output;

}

function lzoom_form($form, &$form_state) {

  $form['input_gene'] = array (
    '#type' => 'textfield',
    '#title' => t('Gene Symbol'),
    '#default_value' => '',
    '#description' => t('Please enter a gene symbol'),
    '#size' => 20,
    '#autocomplete_path' => 'taxonomy/autocomplete/field_genes_diff',
  );

  $study_list = array(1 => 'IGAP GWAS',
                      2 => 'AMP-AD GWAS');

  $form['study'] = array(
       '#type' => 'select',
       '#title' => t('Study'),
       '#options' => array(0 => t('- Select -')) + $study_list,
       '#default_value' => 1,
       '#description' => t('Please select the study'),
   );


  $form['submit'] = array(
    '#prefix' => '<div class="lzoom-go-inline">',
    '#suffix' => '</div>',
    '#type' => 'submit',
    '#value' => t('Go'),
    '#ajax' => array(
      'callback' => 'ajax_lzoom_callback',
      'wrapper'  => 'lzoom-plot',
      'effect'   => 'fade',
     ),
  );


  // Define default study as IGAP
  //if (!isset($form_state['values'])) {
  //  $_SESSION['lzoom_study'] = "IGAP_stage_1.tsv";
  //}

  // Define default data region as APOE
  $data_region='19:44909011-45912650';
  $study = 1;
  $output = lzoom_viz($data_region, $study);

  $form['wrapper'] = array(
    '#markup' => '<div id="lzoom-plot">' . $output . '</div>',
  );


	return $form;
}


function ajax_lzoom_callback($form, $form_state) {

  $study = $form_state['values']['study'];

  // Get region of gene and return the new lzoom-plot div
  $data_region = get_gene_info($form_state['values']['input_gene']);

  $start = intval($data_region['start'])-100000;
  $end = intval($data_region['end']) + 100000;

  $data_region = $data_region['chr'] . ':' . $start . '-' . $end;
  //dsm($data_region);

  return '<div id="lzoom-plot">' .  lzoom_viz($data_region, $study) . '</div>';

}

function get_gene_info($input_gene) {

  $base_api = "http://portaldev.sph.umich.edu/api/v1/annotation/genes/?filter=";
  $filter = "source in 2 and gene_name eq '" . $input_gene . "'";
  $full_url = $base_api . rawurlencode(utf8_encode(($filter)));
  //dsm($full_url);

  $gene_source = drupal_http_request($full_url);
  $gene_data = $gene_source->data;
  $gene_data = drupal_json_decode($gene_data);
  //dsm($gene_data);

  $chr = $gene_data['data'][0]['chrom'];
  $start = $gene_data['data'][0]['start'];
  $end = $gene_data['data'][0]['end'];
  //dsm($chr);

  return array('chr'=>$chr, 'start'=>$start, 'end'=>$end);

}


?>
