<?php
/**
 * @file
 * Module file for LocusZoom Services.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function lzoom_services_services_resources() {
  $resources = array();

//Include the necessary inc files.
  module_load_include('inc', 'lzoom_services', 'includes/lzoom_services.services');

//Service Apis for contents.
  $resources += lzoom_services_resource();

  return $resources;
}

/**
 * [housing_schemes_services_resource_retrieve] definition.
 * Returns the information about a housing scheme.
 * @param $nid
 *   The nid of the housing_scheme node.
 * @return array
 *	The node processed information array.
 */
function lzoom_services_resource_retrieve($nid) {

  $full_url = "https://portaldev.sph.umich.edu/api/v1/statistic/single/results/?filter=analysis%20in%203%20and%20chromosome%20in%20%20%2710%27%20and%20position%20ge%20114550452%20and%20position%20le%20115067678";
  $my_test = drupal_http_request($full_url);
  $data = drupal_json_decode($my_test->data);

  return $data;

}


?>
