<?php
/**
 * @file
 * Module file for LocusZoom Services.
 * Contains the resource declarations for the service APIs
 * and other commons functions/hooks. if necessary
 */

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data.
 */
function lzoom_services_services_resources() {
  $resources = array();

//Include the necessary inc files.
  module_load_include('inc', 'lzoom_services', 'includes/lzoom_services.services');

//Service Apis for contents.
  $resources += lzoom_services_resource();

  return $resources;
}

/**
 * [housing_schemes_services_resource_retrieve] definition.
 * Returns the information about a housing scheme.
 * @param $nid
 *   The nid of the housing_scheme node.
 * @return array
 *	The node processed information array.
 */
function lzoom_services_resource_retrieve($filter) {


  $full_url = "https://portaldev.sph.umich.edu/api/v1/statistic/single/results/?filter=" .  rawurlencode(utf8_encode(($filter)));

 	$my_test = drupal_http_request($full_url);
	$data = drupal_json_decode($my_test->data);

 	return $data;

	//return array('filter_string' => $full_url);
}


?>
