<?php

// Show PHP errors (during development only)
    error_reporting(E_ALL | E_STRICT);
    ini_set("display_errors", 2);

/**
* Implements hook_menu().
*/
function pmap2_menu() {
  $items = array();
    $items['pmap2'] = array(
    'title' => 'Abbvie Pathways',
    'description' => 'Abbvie Pathways Analysis',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pmap2_form'),
    'access callback' => 'user_is_logged_in',
  );

  return $items;
}

/**
 * Implements hook_form().
 */
function pmap2_form() {

  $path = libraries_get_path('d3.pmap2');
  libraries_load('d3.pmap2');
  //dsm($path);


// Import your static HTML page
  $form['html'] = array(
    '#type' => 'item',
    '#markup' => file_get_contents($path .'/index.html'),
  );
  return $form;

}







?>
